version: '3.4'

services:
  ucare.web:
    image: ucareweb:dev
    container_name: UCare.Web
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "UCare.Web"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_ucare.web$
    volumes:
      - C:\Proyectos\WebApps\transglobal-ucare\UCARE NET\back\UCare.Web:/app
      - C:\Proyectos\WebApps\transglobal-ucare\UCARE NET\back:/src
      - C:\Users\mati_\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_ucare.web$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_ucare.web$ \"/app/bin/Release/net6.0/UCare.Web.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true